version: "3.9"

services:

  service1:
    build:
      context: ./User_Service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - ./User_Service:/microservice1/
    depends_on:
      - postgres_db
      - broker

  postgres_db:
    image: postgres:latest # Use the official PostgreSQL image
    restart: always
    container_name: PostgresCont
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgresdatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

 
volumes:
  postgres_db:
    driver: local

networks:
  default:
    driver: bridge
